Added CreditUsed Report and CreditTicket Report
pluginsGLPI/credit pull request #40
Opened 2018-08-31 10:58 UTC by xacobofg

CreditUsed Report: lists each credit spent.
CreditTicket Report: lists each credit voucher information.
old pull request #23 
#34

2019-09-04 10:54 UTC, gperrot commented
Hello,

does this report focntion still working?

because i tried to add it without success, tried to check code but i'm not really good as php ;(

regards

2020-01-24 06:49 UTC, stonebuzz commented
Can you rebase you branch develop to be compatible with glpi 9.4

Best regards

2020-02-04 12:37 UTC, xacobofg commented
Hello.
I've rebase the branch

2021-06-21 07:29 UTC, MarinBerthome commented
Will be great to add the possibility to search tickets with credits criteria.

2022-01-20 18:24 UTC, OlivierPDL commented
![image](https://user-images.githubusercontent.com/28402746/150398761-dd80362d-0f65-48c4-925c-11742dc4a9c6.png)

2022-01-20 18:25 UTC, OlivierPDL commented
![image](https://user-images.githubusercontent.com/28402746/150399018-ba24ac64-9565-485c-af58-5fbb791399c7.png)

2024-02-22 08:39 UTC, stonebuzz commented
Please apply my suggestion

best regards

2024-02-22 11:30 UTC, Rom1-B requested changes
Hello,
I haven't pointed out all the cases, but you must be careful to use English in the names of variables/functions and comments.
Please correct.

2024-02-22 11:30 UTC, Rom1-B commented on report/creditused/creditused.php
> +//Filtro fecha
English comments, please

2024-02-22 11:30 UTC, Rom1-B commented on report/creditused/creditused.php
> +                     new PluginReportsColumn('categoria', $LANG['creditused'][1]),
```suggestion
                     new PluginReportsColumn('category', $LANG['creditused'][1]),
```

2024-02-22 12:32 UTC, stonebuzz requested changes

2024-02-22 12:32 UTC, stonebuzz commented on report/creditused/creditused.php
> +$choices = [0=>'--', 2 =>$LANG['creditused_active'][1], 1 => $LANG['creditused_active'][0]];
```suggestion
  $choices = [
    0 => '--',
    2 => $LANG['creditused_active'][1],
    1 => $LANG['creditused_active'][0],
];
```

2024-02-22 12:32 UTC, stonebuzz commented on report/creditused/creditused.php
> +   if ($filter_active->getParameterValue()==2) {
```suggestion
   if ($filter_active->getParameterValue() == 2) {
```

2024-02-22 12:32 UTC, stonebuzz commented on report/creditvoucher/creditvoucher.php
> +$choices = [0=>'--', 2 =>$LANG['creditvoucher_active'][1], 1 => $LANG['creditvoucher_active'][0]];
```suggestion
$choices = [
    0 => '--',
    2 => $LANG['creditvoucher_active'][1],
    1 => $LANG['creditvoucher_active'][0],
];
```

2024-02-22 12:32 UTC, stonebuzz commented on report/creditvoucher/creditvoucher.php
> +   if ($filter_active->getParameterValue()==2) {
```suggestion
   if ($filter_active->getParameterValue() == 2) {
```

2025-06-25 12:18 UTC, stonebuzz commented
Since this pull request hasn't seen any activity for a while, I'm closing it for now.
Feel free to reopen it if needed, ideally by updating it based on the feedback previously provided.

2025-06-25 12:18 UTC, closed without merging