fix: global config in ticket header
pluginsGLPI/credit pull request #89
Opened 2022-11-16 10:11 UTC by Rom1-B

### Changes description

The global configuration appeared in the ticket header. This was not consistent.

Before:
![image](https://user-images.githubusercontent.com/8530352/202152429-4a64bfc5-4c8d-4e48-879f-64f724503d8e.png)

### Checklist

Please check if your PR fulfills the following specifications:

- [ ] Tests for the changes have been added
- [ ] Docs have been added/updated

### References

Close: #N/A

2022-11-16 13:43 UTC, cedric-anne commented
This is not the global configuration, but the default configuration for current ticket.

It has been done intentionnaly in #60. A solution could be to introduce a dedicated right for this, so people may disable this right to not see these fields.

2022-11-30 08:11 UTC, cedric-anne requested changes
See my previous comment.

2023-04-11 14:02 UTC, cedric-anne requested changes

2023-04-11 14:02 UTC, cedric-anne commented on inc/ticketconfig.class.php
>        }
We should remove this.
```suggestion
```

2023-04-11 14:02 UTC, cedric-anne commented on inc/ticketconfig.class.php
> +   const TICKET_FORM = 2048;
A migration should be added to add `plugin_creditticketconfig:TICKET_TAB&TICKET_FORM` right when `plugin_creditticketconfig` does not exist yet and user has the `entity:UPDATE` right.

The `Migration::addRight()` method could probably be used for this.

2023-06-07 09:13 UTC, Rom1-B commented
Replaced by https://github.com/pluginsGLPI/credit/pull/96

2023-06-07 09:13 UTC, closed without merging